language: java
sudo: true
before_script:
  - sudo sysctl -w vm.max_map_count=262144
jdk:
  - oraclejdk8
after_success:
  - mvn clean verify
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/04820972e9b664f3140c
    on_success: change
    on_failure: always
    on_start: never
